### PR TITLE
Npm@8

### PR DESCRIPTION
**Pull request by barmac**

### CODE REVIEW

**Comment by nikku** [comment]
Needs conflict resolution.

**Comment by pinussilvestrus** [comment]
Shouldn't we update the [GitHub action](https://github.com/camunda-cloud/zeebe-bpmn-moddle/blob/master/.github/workflows/CI.yml#L9) as well?

**Comment by barmac** [comment]
It uses already npm@8: https://github.com/actions/runner-images/blob/ubuntu20/20220821.1/images/linux/Ubuntu2004-Readme.md#package-management

**Comment by pinussilvestrus** [comment]
I see; good catch. Shouldn't we verify it works with node@16 regardless? I see we start doing it in [other projects](https://github.com/bpmn-io/moddle-xml/pull/65/files).

Node@16 is likely the version we use for development, at least tools like `n` promote it.

**Comment by nikku** [comment]
Let's update the action to use `node@16`.

**Review by pinussilvestrus — APPROVED** [review]

**Pull request merged**
